default_language_version:
    python: python3.11
repos:
  - repo: https://github.com/PyCQA/autoflake
    rev: v1.7.8
    hooks:
      - id: autoflake
        exclude: alembic/

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        exclude: alembic/
