version: "0.2"
ignorePaths:
  - .gitignore
  - requirements.txt
  - alembic*
allowCompoundWords: true
dictionaries:
  - python
words:
  - anyio
  - apscheduler
  - clsname
  - grnd
  - isort
  - isouter
  - Misha
  - mypy
  - nesseccery
  - ondelete
  - onupdate
  - psycopg
  - pydantic
  - pytest
  - sqlalchemy
  - testdb
  - trgm
  - venv
  - vybornyy
ignoreWords: []
import: []
enableFiletypes:
  - dockercompose
  - ini
  - makefile
  - markdown
  - toml
